# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
release:
  draft: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - image_templates:
    - "ghcr.io/fybrik/{{.ProjectName}}:latest"
    - "ghcr.io/fybrik/{{.ProjectName}}:{{ .Version }}"
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
changelog:
  sort: asc
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^style:'
      - '^refactor:'
      - '^build(deps):'
